#!/bin/bash

export COPYFILE_DISABLE=1
export VERSION=0.5.2

rm -rf *${VERSION}*.ipk *.deb
find . -name '*~' -delete

# Main
rm -rf data.tar.gz control.tar.gz
cd src/data
sed -i "s/^VERSION=\".*\"$/VERSION=\"${VERSION}\"/" www/cgi-bin/waterfall-lib.lua
tar cf ../../data.tar `find . -type f | grep -v DS_Store | grep -v .pl | grep -v .pm`
cd ../control
sed -i "s/^Version: .*$/Version: ${VERSION}/" control
tar cfz ../../control.tar.gz .
cd ../..
gzip data.tar
COPYFILE_DISABLE=1 tar cfz waterfall_${VERSION}_all.ipk control.tar.gz data.tar.gz debian-binary

rm -rf data.tar.gz control.tar.gz *.deb
